### ISSUE TITLE
Local or remote link: Handle file locations of the file

### ISSUE THREAD

**Issue by royscheeren** [ASCS-eV/envited-x-data-space#172]
# Scope
We need to know where the asset file is going to live.

# Definition of done
- [x] Extract the datalink property
- [x] Determine if its a "local" or remote link
- [x] Leave external link in the modified manifest.json

**Comment by jdsika** [comment]
Important:
A process definition is necessary and software/libraries for "incremental authorization" need to be available and documented because the owner of the REMOTE is responsible to provide access to the file through this process. The same way ENVITED is providing the access for the self-hosted data
